# (The MIT License)
#
# SPDX-FileCopyrightText: Copyright (c) 2022-2025 Yegor Bugayenko
# SPDX-License-Identifier: MIT
---
# yamllint disable rule:line-length
docker:
  image: yegor256/rultor-ruby
assets:
  rubygems.yml: yegor256/home#assets/rubygems.yml
install: |
  pdd -f /dev/null
  sudo bundle install --no-color "--gemfile=$(pwd)/Gemfile"
release:
  pre: false
  script: |-
    bundle exec rake
    rm -rf *.gem
    sed -i "s/0\.0\.0/${tag}/g" lib/mergem/version.rb
    git add lib/mergem/version.rb
    git commit -m "version set to ${tag}"
    gem build mergem.gemspec
    chmod 0600 ../rubygems.yml
    gem push *.gem --config-file ../rubygems.yml
merge:
  script: |-
    bundle exec rake
